# Generated by Django 4.0.1 on 2022-02-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='password',
            new_name='email2',
        ),
    ]
